/**
 * PDF Report Generator
 */
import PDFDocument from 'pdfkit';
import { AnalysisResult } from '../types';
import { Writable } from 'stream';

export class PDFGenerator {
  /**
   * Generate PDF report from analysis result
   */
  generate(result: AnalysisResult, outputStream: Writable): Promise<void> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });

        doc.pipe(outputStream);

        // Title
        doc.fontSize(20).text('Telco MOP Analysis Report', { align: 'center' });
        doc.moveDown();

        // Metadata
        doc.fontSize(10).text(`Category: ${result.metadata.category}`, { align: 'left' });
        doc.text(`Analyzed: ${new Date(result.metadata.analyzedAt).toLocaleString()}`);
        doc.text(`Processing Time: ${result.metadata.processingTimeMs}ms`);
        doc.text(`Confidence: ${(result.confidence * 100).toFixed(0)}%`);
        doc.moveDown();

        // Total Score
        doc.fontSize(16).text('Overall Quality Score', { underline: true });
        doc.fontSize(14).fillColor(this.getScoreColor(result.totalScore))
          .text(`${result.totalScore.toFixed(1)} / 10`, { align: 'left' });
        doc.fillColor('black');
        doc.moveDown();

        // Section Scores
        doc.fontSize(16).text('Section Scores', { underline: true });
        doc.moveDown(0.5);

        this.addSectionScore(doc, 'Pre-Checks', result.scores.preChecks);
        this.addSectionScore(doc, 'Operation Steps', result.scores.operationSteps);
        this.addSectionScore(doc, 'Rollback Steps', result.scores.rollbackSteps);
        doc.moveDown();

        // Recommendations
        if (result.recommendations.length > 0) {
          doc.fontSize(16).text('Recommendations', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(10);
          result.recommendations.forEach((rec, idx) => {
            doc.text(`${idx + 1}. ${rec}`, { indent: 20 });
          });
          doc.moveDown();
        }

        // Evidence
        if (result.evidence.length > 0) {
          doc.fontSize(16).text('Industry Best Practice References', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(10);
          result.evidence.slice(0, 5).forEach((ev, idx) => {
            doc.text(`${idx + 1}. ${ev.title}`, { indent: 20, continued: false });
            doc.fontSize(8).fillColor('blue').text(ev.link, { indent: 30 });
            doc.fillColor('black').fontSize(10);
            doc.moveDown(0.5);
          });
        }

        // Footer
        doc.fontSize(8).fillColor('gray')
          .text(
            'Generated by Telco MOP Analysis Agent',
            50,
            doc.page.height - 50,
            { align: 'center' }
          );

        doc.end();

        outputStream.on('finish', resolve);
        outputStream.on('error', reject);
      } catch (error) {
        reject(error);
      }
    });
  }

  private addSectionScore(doc: PDFKit.PDFDocument, name: string, score: any): void {
    doc.fontSize(12).text(`${name}:`, { continued: true });
    doc.fillColor(this.getScoreColor(score.score))
      .text(` ${score.score.toFixed(1)}/10`, { align: 'left' });
    doc.fillColor('black').fontSize(9);
    
    const breakdown = score.breakdown;
    doc.text(
      `  Presence: ${breakdown.presence.toFixed(1)} | Clarity: ${breakdown.clarity.toFixed(1)} | ` +
      `Verifiability: ${breakdown.verifiability.toFixed(1)} | Safety: ${breakdown.safety.toFixed(1)} | ` +
      `Compliance: ${breakdown.compliance.toFixed(1)}`,
      { indent: 20 }
    );
    doc.moveDown(0.5);
  }

  private getScoreColor(score: number): string {
    if (score >= 8) return 'green';
    if (score >= 6) return 'orange';
    return 'red';
  }
}
